### ISSUE TITLE
Panic on struct field pointing to zero value

### ISSUE THREAD

**Issue by asdine** [go-ozzo/ozzo-validation#15]
When using `ValidateStruct` on a struct that has a field using a pointer to any field that contains a zero value, the validation panics.

```go
package main

import validation "github.com/go-ozzo/ozzo-validation"

type A struct {
	Name *string
}

func (a *A) Validate() error {
	return validation.ValidateStruct(a,
		validation.Field(&a.Name, validation.Length(1, 32)),
	)
}
func main() {
	var a A
	a.Validate()
}

```

```sh
$ go run main.go
panic: reflect: call of reflect.Value.Type on zero Value

goroutine 1 [running]:
panic(0x117440, 0xc420206800)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
reflect.Value.Type(0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/reflect/value.go:1670 +0x224
github.com/go-ozzo/ozzo-validation.Validate(0x119ca0, 0x0, 0xc420193c90, 0x1, 0x1, 0x196, 0xc4202052d0)
```

**Comment by asdine** [comment]
I have updated the issue above, it panics on any field that points to a zero value.
